<a href="https://colab.research.google.com/github/Terrance07/Machine-learning-algorithms/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [30]:
df = pd.read_csv("/content/student_data_100.csv")

In [31]:
df

    Student_ID         Name  Hours_Studied  Attendance  Assignments  Marks
0            1    Student_1              2          61            7     35
1            2    Student_2              4          68            4     35
2            3    Student_3              9          65            9     55
3            4    Student_4              1          65            6     35
4            5    Student_5              9          98            3     66
..         ...          ...            ...         ...          ...    ...
95          96   Student_96              1          82            6     35
96          97   Student_97              4          66            8     37
97          98   Student_98              7          99            5     54
98          99   Student_99              3          71            9     35
99         100  Student_100              3          81            9     41

[100 rows x 6 columns]

In [32]:
df.head()

   Student_ID       Name  Hours_Studied  Attendance  Assignments  Marks
0           1  Student_1              2          61            7     35
1           2  Student_2              4          68            4     35
2           3  Student_3              9          65            9     55
3           4  Student_4              1          65            6     35
4           5  Student_5              9          98            3     66

In [33]:
df.tail()

    Student_ID         Name  Hours_Studied  Attendance  Assignments  Marks
95          96   Student_96              1          82            6     35
96          97   Student_97              4          66            8     37
97          98   Student_98              7          99            5     54
98          99   Student_99              3          71            9     35
99         100  Student_100              3          81            9     41

In [34]:
df.shape

(100, 6)

In [35]:
df.columns

Index(['Student_ID', 'Name', 'Hours_Studied', 'Attendance', 'Assignments',
       'Marks'],
      dtype='object')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     100 non-null    int64
 1   Name           100 non-null    object
 2   Hours_Studied  100 non-null    int64
 3   Attendance     100 non-null    int64
 4   Assignments    100 non-null    int64
 5   Marks          100 non-null    int64
dtypes: int64(5), object(1)
memory usage: 4.8+ KB

In [37]:
df.describe()

       Student_ID  Hours_Studied  Attendance  Assignments       Marks
count  100.000000     100.000000  100.000000   100.000000  100.000000
mean    50.500000       5.400000   79.410000     6.230000   45.680000
std     29.011492       2.655279   12.589153     2.273497   10.829141
min      1.000000       1.000000   60.000000     3.000000   35.000000
25%     25.750000       3.000000   69.000000     4.000000   35.000000
50%     50.500000       5.000000   76.500000     6.000000   42.000000
75%     75.250000       8.000000   91.250000     8.000000   54.250000
max    100.000000      10.000000  100.000000    10.000000   72.000000

In [38]:
df.isnull().sum()

Student_ID       0
Name             0
Hours_Studied    0
Attendance       0
Assignments      0
Marks            0
dtype: int64

In [39]:
X = df[['Hours_Studied', 'Attendance', 'Assignments']]
y = df['Marks']

In [40]:
print(X)
print(y)

    Hours_Studied  Attendance  Assignments
0               2          61            7
1               4          68            4
2               9          65            9
3               1          65            6
4               9          98            3
..            ...         ...          ...
95              1          82            6
96              4          66            8
97              7          99            5
98              3          71            9
99              3          81            9

[100 rows x 3 columns]
0     35
1     35
2     55
3     35
4     66
      ..
95    35
96    37
97    54
98    35
99    41
Name: Marks, Length: 100, dtype: int64

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

    Hours_Studied  Attendance  Assignments
55              7          82            9
88              1          65            9
26              9          76            9
42              8          64            5
69              1          97           10
..            ...         ...          ...
60              4          64           10
71              2          71            4
14              1          74            7
92              2          69            3
51              6          64            6

[80 rows x 3 columns]
    Hours_Studied  Attendance  Assignments
83              9          79            4
53             10          90            6
70              9          70            3
45              9          72            7
44              9          98            9
39              6          91            3
22              6          85            7
80              6          64            6
10              6          98            7
0               2          61            7
18              5          64            5
30              7          98            4
73             10          75            3
33              2          94            7
90              5          70           10
4               9          98            3
76              7          68            7
77              6          64            3
12              2          95            7
31              7          98           10
55    57
88    35
26    68
42    46
69    36
      ..
60    39
71    35
14    35
92    35
51    39
Name: Marks, Length: 80, dtype: int64
83    55
53    72
70    56
45    61
44    70
39    41
22    45
80    40
10    49
0     35
18    37
30    55
73    64
33    37
90    46
4     66
76    50
77    38
12    38
31    66
Name: Marks, dtype: int64

In [43]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [44]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)
model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 1)              │             2 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 64)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,755 (10.76 KB)

 Trainable params: 2,755 (10.76 KB)

 Non-trainable params: 0 (0.00 B)